export const heroData = [
  {
    ID: 1,
    Category: "icecreams",
    Title: "Icecream",
    Desc: "Chocolate & vanilla",
    Calories: 250,
    ImgUrl: 'c1.png',
  },
  {
    ID: 2,
    Category: "Fruits",
    Title: "Strawberries",
    Desc: "Fresh Strawberries",
    Calories: 50,
    ImgUrl: 'c1.png',
  },
  {
    ID: 3,
    Title: "Chicken Kebab",
    Category: "chicken",
    Desc: "Mixed Kebab Plate",
    Calories: 320,
    ImgUrl: 'c1.png',
  },
  {
    ID: 4,
    Title: "Fish Kebab",
    Category: "fish",
    Desc: "Mixed Fish Kebab",
    Calories: 280,
    ImgUrl: 'c1.png',
  },
  {
    ID: 5,
    Title: "Chicken Kebab",
    Category: "chicken",
    Desc: "Mixed Kebab Plate",
    Calories: 320,
    ImgUrl: 'c1.png',
  },
  {
    ID: 6,
    Title: "Chicken Kebab",
    Category: "chicken",
    Desc: "Mixed Kebab Plate",
    Calories: 320,
    ImgUrl: 'c1.png',
  },
  {
    ID: 7,
    Title: "Chicken Kebab",
    Category: "chicken",
    Desc: "Mixed Kebab Plate",
    Calories: 320,
    ImgUrl: 'c1.png',
  },
  {
    ID: 8,
    Title: "Chicken Kebab",
    Category: "chicken",
    Desc: "Mixed Kebab Plate",
    Calories: 320,
    ImgUrl: 'c1.png',
  },
  {
    ID: 9,
    Title: "Chicken Kebab",
    Category: "chicken",
    Desc: "Mixed Kebab Plate",
    Calories: 320,
    ImgUrl: 'c1.png',
  },
];


export const categories = [
  {
    id: 1,
    name: "Italian",
    urlParamName: "Italian",
    icon: "🍝",
  },
  {
    id: 2,
    name: "Dessert",
    urlParamName: "Dessert",
    icon: "🍰",
  },
  {
    id: 3,
    name: "Japanese",
    urlParamName: "Japanese",
    icon: "🍱",
  },
  {
    id: 4,
    name: "Healthy",
    urlParamName: "Healthy",
    icon: "🥗",
  },
  {
    id: 5,
    name: "BBQ",
    urlParamName: "BBQ",
    icon: "🍖",
  },
  {
    id: 6,
    name: "Indian",
    urlParamName: "Indian",
    icon: "🍛",
  },
  {
    id: 7,
    name: "Mexican",
    urlParamName: "Mexican",
    icon: "🌮",
  },
];